2024 open data refresh
ccao-data/wiki pull request #47
Opened 2024-11-18 17:53 UTC by wrridgeway

It looks like there are a lot of changes here, but it's really just the two new assets - current-year-only parcel universe and permits - as well as appeals, which I forgot to add when the asset was originally published. There are also minor updates to primary keys, schedules, and broken links.

2025-03-14 17:32 UTC, wrridgeway commented
@njardine Should I remove the _Parcel Status_ asset from this update?

2025-03-17 15:00 UTC, wrridgeway commented
I'm gonna put up a PR here and in data-architecture later changing the name of `default.vw_pin_universe_historic` to `default.vw_pin_universe_historical` and updating links that that change will break.

2025-03-17 20:21 UTC, ccao-jardine requested changes
Tiny change requested. (I kept cornucopia because I like it.)

2025-03-17 22:15 UTC, wrridgeway commented on SOPs/Open-Data.md
> +**Notes**: Contains a cornucopia of locational and spatial data for all parcels in Cook County.
https://github.com/ccao-data/wiki/pull/47/commits/55fb8e6bf7457a7241f9d5e00b0f3b4dc6badc89

2025-03-17 22:42 UTC, jeancochrane approved these changes
Good by me!

2025-03-17 22:42 UTC, jeancochrane commented on SOPs/Open-Data.md
> +**Code:** [default.vw_pin_appeal.sql](https://github.com/ccao-data/data-architecture/blob/master/dbt/models/default/default.vw_pin_appeal.sql)
**[Question, non-blocking]** Not necessary to do right now, but I wonder if at some point we should switch these links to point to the `open_data` models instead of the `default` models?

2025-03-17 22:42 UTC, jeancochrane commented on SOPs/Open-Data.md
>  The Data Department creates and maintains the following open data sets.
**[Question, non-blocking]** What's the utility of maintaining this list of data, instead of linking to [the list of assets on Socrata](https://datacatalog.cookcountyil.gov/?sortBy=newest&pageSize=20&tags=cook+county+assessor)? It seems to me that maintaining this separate documentation introduces the possibility that the two sources of docs will drift from each other, and I don't quite understand what the benefit is.

2025-03-17 22:42 UTC, jeancochrane commented on SOPs/Open-Data.md
> +**Notes**: Refreshed monthly, data is permit rather than PIN-level.
**[Nitpick, non-blocking]** I wouldn't describe the data as being at "permit level" since a permit number can have multiple representations in the data (one for each PIN associated with the permit). I would say instead that "each row describes one parcel's representation in a given permit".

2025-03-18 14:09 UTC, wrridgeway commented on SOPs/Open-Data.md
> +**Code:** [default.vw_pin_appeal.sql](https://github.com/ccao-data/data-architecture/blob/master/dbt/models/default/default.vw_pin_appeal.sql)
This is a good question. I'm not sure... the `open_data` models just point to the `default` models where conditionals and joins actually exist, but they are what feeds the open data assets.

2025-03-18 14:15 UTC, wrridgeway commented on SOPs/Open-Data.md
>  The Data Department creates and maintains the following open data sets.
I think we did this because all of those resources don't scratch a particular itch, a quick simple list of our open data assets along with core metadata that's easy to read for laymen.

- That socrata list has 30 items on it, many of which are no longer maintained and users have to click through them and scroll through quite a lot of information in order to see their metadata.
- The exposure configs are useful for people who know what in the world they are, but this documentation is intended to server a broader audience both in and outside the office.

This is a good point, though.. perhaps we could move away from such a static markdown document and find a way to use the exposure and docs yamls to help populate this section of the wiki.

2025-03-18 14:26 UTC, ccao-jardine approved these changes

2025-03-18 15:14 UTC, merged